package com.siyu.seatapropertybeanmapemptyproblem.dao;


import com.siyu.seatapropertybeanmapemptyproblem.model.QrtzJobDetails;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface QrtzJobDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int deleteByPrimaryKey(QrtzJobDetails key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int insert(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int insertSelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    List<QrtzJobDetails> selectByJobName(@Param("jobName") String jobName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int updateByPrimaryKeySelective(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(QrtzJobDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QRTZ_JOB_DETAILS
     *
     * @mbg.generated Tue Sep 25 13:42:05 CST 2018
     */
    int updateByPrimaryKey(QrtzJobDetails record);


}